### Guard::Shoryuken
#  available options:
#  - :verbose
#  - :queue (defaults to "default") can be an array
#  - :concurrency (defaults to 1)
#  - :timeout
#  - :environment (corresponds to RAILS_ENV for the Shoryuken worker)
guard 'shoryuken', :environment => 'development' do
  watch(%r{^workers/(.+)\.rb$})
end
